window.CALPRO_SUPABASE_URL = 'https://sfublbjfojukmwqhgmev.supabase.co';
window.CALPRO_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmdWJsYmpmb2p1a213cWhnbWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4MzIxOTAsImV4cCI6MjA4NTQwODE5MH0.4HfouKEDbvF6aZ7Vmr0G1Vf-I0yvDYpVkPlNaExlaB8';
window.CALPRO_SUPABASE_REDIRECT_URL = 'https://xkekox.github.io/calistenia-pro/app.html';
